- hosts: all
  gather_facts: False
  become: no
  tasks:
    - debug:
        var: inventory_hostname
    - name: install console vim
      package:
        name: [vim-nox, neovim]
        state: present
      become: yes

    - name: get home dir variable
      shell: echo $HOME
      register: home

    - name: install vim plug
      command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: copy nvim config to the remote
      copy:
        src: 'nvim/'
        dest: "{{ home.stdout }}/.config/nvim/"
        backup: yes
